curl -X POST https://flex-api.twilio.com/v1/FlexFlows \
--data-urlencode "IntegrationType=studio" \
--data-urlencode "Enabled=True" \
--data-urlencode "Integration.FlowSid=FW..." \
--data-urlencode "ContactIdentity=telerivet" \
--data-urlencode "FriendlyName=Telerivet Flex Flow" \
--data-urlencode "ChannelType=custom" \
--data-urlencode "ChatServiceSid=IS..." \
--data-urlencode "LongLived=true" \
--data-urlencode "JanitorEnabled=true" \
-u ACCOUNT_SID:AUTH_TOKEN